In [1]:
# Dependencies
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
# Load in csv
city_data = pd.read_csv("raw_data/city_data.csv")
city_data

                     city  driver_count      type
0              Kelseyland            63     Urban
1              Nguyenbury             8     Urban
2            East Douglas            12     Urban
3           West Dawnfurt            34     Urban
4          Rodriguezburgh            52     Urban
5       South Josephville             4     Urban
6        West Sydneyhaven            70     Urban
7             Travisville            37     Urban
8             Torresshire            70     Urban
9               Lisaville            66     Urban
10              Mooreview            34     Urban
11             Smithhaven            67     Urban
12            Carrollfort            55     Urban
13        Port Josephfurt            28     Urban
14       Lake Jeffreyland            15     Urban
15            South Louis            12     Urban
16             West Peter            61     Urban
17        Kimberlychester            13     Urban
18             Alyssaberg            67     Urban
19               Sarabury            46     Urban
20            Yolandafurt             7     Urban
21            Edwardsbury            11     Urban
22        New Andreamouth            42     Urban
23              New David            31     Urban
24             Arnoldview            41     Urban
25           Williamshire            70     Urban
26               Lisatown            47     Urban
27              New Aaron            60     Urban
28            Swansonbury            64     Urban
29             Fosterside            69     Urban
..                    ...           ...       ...
96               New Lynn            20  Suburban
97              Port Jose            11  Suburban
98               Johnland            13  Suburban
99              West Tony            17  Suburban
100            Port James             3  Suburban
101          Campbellport            26  Suburban
102          Port Guytown            26  Suburban
103           Webstertown            26  Suburban
104             Clarkstad            21  Suburban
105       North Tracyfort            18  Suburban
106           Martinmouth             5  Suburban
107      New Jessicamouth            22  Suburban
108  South Elizabethmouth             3     Rural
109         East Troybury             3     Rural
110             Kinghaven             3     Rural
111          New Johnbury             6     Rural
112              Erikport             3     Rural
113           Jacksonfort             6     Rural
114           Shelbyhaven             9     Rural
115           Matthewside             4     Rural
116          Kennethburgh             3     Rural
117          South Joseph             3     Rural
118         Manuelchester             7     Rural
119           Stevensport             6     Rural
120         North Whitney            10     Rural
121          East Stephen             6     Rural
122           East Leslie             9     Rural
123        Hernandezshire            10     Rural
124             Horneland             8     Rural
125        West Kevintown             5     Rural

[126 rows x 3 columns]

In [5]:
city_data_clean = pd.DataFrame({'type': city_data.groupby('city').first()['type'],
                                'driver_count': city_data.groupby('city').sum()['driver_count']}).reset_index()
city_data_clean

                     city  driver_count      type
0            Alvarezhaven            21     Urban
1              Alyssaberg            67     Urban
2              Anitamouth            16  Suburban
3            Antoniomouth            21     Urban
4            Aprilchester            49     Urban
5              Arnoldview            41     Urban
6            Campbellport            26  Suburban
7             Carrollbury             4  Suburban
8             Carrollfort            55     Urban
9               Clarkstad            21  Suburban
10            Conwaymouth            18  Suburban
11              Davidtown            73     Urban
12              Davistown            25     Urban
13        East Cherylfurt             9  Suburban
14           East Douglas            12     Urban
15              East Erin            43     Urban
16   East Jenniferchester            22  Suburban
17            East Leslie             9     Rural
18           East Stephen             6     Rural
19          East Troybury             3     Rural
20            Edwardsbury            11     Urban
21               Erikport             3     Rural
22               Eriktown            15     Urban
23             Floresberg             7  Suburban
24             Fosterside            69     Urban
25         Hernandezshire            10     Rural
26              Horneland             8     Rural
27            Jacksonfort             6     Rural
28              Jacobfort            52     Urban
29              Jasonfort            25  Suburban
..                    ...           ...       ...
95              South Roy            35     Urban
96   South Shannonborough             9  Suburban
97            Spencertown            68     Urban
98            Stevensport             6     Rural
99            Stewartview            49     Urban
100           Swansonbury            64     Urban
101            Thomastown             1  Suburban
102            Tiffanyton            21  Suburban
103           Torresshire            70     Urban
104           Travisville            37     Urban
105            Vickimouth            13     Urban
106           Webstertown            26  Suburban
107           West Alexis            47     Urban
108           West Brandy            12     Urban
109      West Brittanyton             9     Urban
110         West Dawnfurt            34     Urban
111             West Evan             4  Suburban
112      West Jefferyfurt            65     Urban
113        West Kevintown             5     Rural
114            West Oscar            11     Urban
115    West Pamelaborough            27  Suburban
116         West Paulport             5  Suburban
117            West Peter            61     Urban
118      West Sydneyhaven            70     Urban
119             West Tony            17  Suburban
120        Williamchester            26  Suburban
121          Williamshire            70     Urban
122           Wiseborough            55     Urban
123           Yolandafurt             7     Urban
124        Zimmermanmouth            45     Urban

[125 rows x 3 columns]

In [ ]:
# Load in csv
ride_df = pd.read_csv("raw_data/ride_data.csv")
ride_df.head()

In [ ]:
city_df.columns

In [ ]:
ride_df.columns

In [ ]:
city_df = pd.DataFrame(city_df)

In [ ]:
ride_df = pd.DataFrame(ride_df)

In [ ]:
#Merged Tabled
merge_table_df = pd.merge(city_data_clean, ride_df, on="city")
merge_table_df

In [ ]:
# Using GroupBy in order to separate the data 
grouped_city_df = merge_table_df.groupby(['city'])

# The object returned is a "GroupBy" object and cannot be viewed normally...
print(grouped_city_df)

# In order to be visualized, a data function must be used...
grouped_city_df.count.head(10)

In [ ]:
avg_fare = grouped_city["fare"].mean()
avg_fare.head()

In [ ]:
#Total # Rides/City
total_rides_city=grouped_city["ride_id"].count()
total_rides_city.head()

In [ ]:
city_df.count()

In [ ]:
total_drivers_city=grouped_city_df["driver_count"].count()
total_drivers_city.head()

In [ ]:
city_type=grouped_city_df["type"].count()
city_type.head()